Repository WonPage/MyongjiCamp-BackEnd, pull requests merged in 2024-08, with the labels that each got.

#2 [CI] ci/cd 파이프라인 구축, RDS 연결, REDIS 캐시 생성 및 연결, 환경변수 설정
  .ebextensions-dev/00-makeFiles.config
  .ebextensions-dev/01-set-timezone.config
  .github/workflows/dev_deploy.yml
  .platform/nginx.conf
  .platform/nginx/conf.d/client_max_body_size.conf
  Procfile
  src/main/java/com/won/myongjiCamp/controller/api/RootApiController.java
  src/main/java/com/won/myongjiCamp/service/S3ImageService.java
  src/main/resources/application.yml
Labels: :sparkles: Feat, :construction_worker: Ci

#3 [FIX] dev_deploy.yml 파일 수정
  .github/workflows/dev_deploy.yml
Labels: :hammer: Fix

#4 [FIX] dev_deploy.yml 파일 수정
  .github/workflows/dev_deploy.yml
Labels: :hammer: Fix

#5 [FIX] dev_deploy.yml 파일 수정
  .github/workflows/dev_deploy.yml
Labels: :hammer: Fix

#6 [FIX] dev_deploy.yml 파일 수정
  .github/workflows/dev_deploy.yml
Labels: :hammer: Fix

#7 [FIX] dev_deploy.yml 파일 수정
  .github/workflows/dev_deploy.yml
Labels: :hammer: Fix

#8 [FIX] dev_deploy.yml 파일 수정
  .github/workflows/dev_deploy.yml
Labels: :hammer: Fix

#9 [FIX] dev_deploy.yml 파일 수정
  .github/workflows/dev_deploy.yml
Labels: :bug: Bug

#10 [FIX] maven -> gradle 변환작업
  .github/workflows/dev_deploy.yml
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  build.gradle
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  mvnw
  mvnw.cmd
  pom.xml
  settings.gradle
  src/main/resources/application.yml
Labels: :hammer: Fix

#12 [FIX] 테스트 코드 삭제 & scrap 리스트 boardType, imageUrl 추가
  src/main/java/com/won/myongjiCamp/controller/api/ApplicationApiController.java
  src/main/java/com/won/myongjiCamp/controller/api/BoardApiController.java
  src/main/java/com/won/myongjiCamp/controller/api/CommentApiController.java
  src/main/java/com/won/myongjiCamp/controller/api/MemberApiController.java
  src/main/java/com/won/myongjiCamp/controller/api/ReportApiController.java
  src/main/java/com/won/myongjiCamp/controller/api/ResumeApiController.java
  src/main/java/com/won/myongjiCamp/controller/api/ScrapApiController.java
  src/main/java/com/won/myongjiCamp/dto/BoardListResponseDto.java
Labels: :hammer: Fix

#13 [FIX] 0818 피드백 내용 수정
  src/main/java/com/won/myongjiCamp/controller/api/ApplicationApiController.java
  src/main/java/com/won/myongjiCamp/controller/api/BoardApiController.java
  src/main/java/com/won/myongjiCamp/model/board/CompleteBoard.java
  src/main/java/com/won/myongjiCamp/model/board/RecruitBoard.java
  src/main/java/com/won/myongjiCamp/repository/CompleteRepository.java
  src/main/java/com/won/myongjiCamp/service/ApplicationService.java
  src/main/java/com/won/myongjiCamp/service/BoardService.java
  src/main/java/com/won/myongjiCamp/service/CompleteService.java
  src/main/java/com/won/myongjiCamp/service/RecruitService.java
Labels: :sparkles: Feat, :hammer: Fix

#14 [BUG] 게시물 상세보기에서 completeBoard null에러 해결
  src/main/java/com/won/myongjiCamp/controller/api/BoardApiController.java
Labels: :bug: Bug

#15 [FEAT & FIX] 240818 알림 기능 구현 알림 기능 및 FCM으로 변경
  .gitignore
  build.gradle
  src/main/java/com/won/myongjiCamp/controller/api/ApplicationApiController.java
  src/main/java/com/won/myongjiCamp/controller/api/CommentApiController.java
  src/main/java/com/won/myongjiCamp/controller/api/FcmApiController.java
  src/main/java/com/won/myongjiCamp/controller/api/MemberApiController.java
  src/main/java/com/won/myongjiCamp/controller/api/NotificationApiController.java
  src/main/java/com/won/myongjiCamp/dto/CommentDto.java
  src/main/java/com/won/myongjiCamp/dto/CommentResponseDto.java
  src/main/java/com/won/myongjiCamp/dto/Fcm/FcmMessageDto.java
  src/main/java/com/won/myongjiCamp/dto/Fcm/FcmSendDto.java
  src/main/java/com/won/myongjiCamp/dto/NotificationDto.java
  src/main/java/com/won/myongjiCamp/dto/NotificationResponseDto.java
  src/main/java/com/won/myongjiCamp/dto/PageDto.java
  src/main/java/com/won/myongjiCamp/dto/TokenDto.java
  src/main/java/com/won/myongjiCamp/model/Notification.java
  src/main/java/com/won/myongjiCamp/model/NotificationMessage.java
  src/main/java/com/won/myongjiCamp/model/NotificationStatus.java
  src/main/java/com/won/myongjiCamp/model/board/Board.java
  src/main/java/com/won/myongjiCamp/model/board/Comment.java
  src/main/java/com/won/myongjiCamp/model/board/RecruitBoard.java
  src/main/java/com/won/myongjiCamp/repository/NotificationRepository.java
  src/main/java/com/won/myongjiCamp/service/CommentService.java
  src/main/java/com/won/myongjiCamp/service/FcmService.java
  src/main/java/com/won/myongjiCamp/service/NotificationService.java
  src/main/java/com/won/myongjiCamp/service/RecruitService.java
Labels: :sparkles: Feat, :hammer: Fix

#20 [CI] dev_deploy.yml 수정
  .github/workflows/dev_deploy.yml
Labels: :hammer: Fix

#21 [FIX] dev_deploy.yml 수정
  .github/workflows/dev_deploy.yml
Labels: :hammer: Fix

#22 [FIX] dev_deploy.yml 수정
  .github/workflows/dev_deploy.yml
Labels: :hammer: Fix

#23 [FIX] .gitignore 수정
  .github/workflows/dev_deploy.yml
  .gitignore
  src/main/resources/firebase/mjcamp-67915-firebase-adminsdk-ydkil-e1224a7415.json
Labels: :hammer: Fix

#24 [FIX] dev_deploy.yml 수정
  .github/workflows/dev_deploy.yml
Labels: :hammer: Fix

#25 [FIX] deploy.yml 파일 수정
  .github/workflows/dev_deploy.yml
Labels: :hammer: Fix

#26 [FIX] dev_deploy.yml 수정
  .github/workflows/dev_deploy.yml
Labels: :hammer: Fix

#27 [BUG] 글 삭제 시 오류 수정
  src/main/java/com/won/myongjiCamp/controller/api/BoardApiController.java
  src/main/java/com/won/myongjiCamp/service/CompleteService.java
  src/main/java/com/won/myongjiCamp/service/RecruitService.java
Labels: :bug: Bug

#29 [FIX] Redis 전체 데이터 삭제 로직 주석 처리
  src/main/java/com/won/myongjiCamp/controller/RedisInitializer.java
Labels: :hammer: Fix

#30 [FIX] 알림 에러 수정
  src/main/java/com/won/myongjiCamp/controller/api/ApplicationApiController.java
  src/main/java/com/won/myongjiCamp/controller/api/BoardApiController.java
  src/main/java/com/won/myongjiCamp/controller/api/CommentApiController.java
  src/main/java/com/won/myongjiCamp/controller/api/FcmApiController.java
  src/main/java/com/won/myongjiCamp/controller/api/MemberApiController.java
  src/main/java/com/won/myongjiCamp/controller/api/ReportApiController.java
  src/main/java/com/won/myongjiCamp/controller/api/ResumeApiController.java
  src/main/java/com/won/myongjiCamp/controller/api/ScrapApiController.java
  src/main/java/com/won/myongjiCamp/dto/NotificationDto.java
  src/main/java/com/won/myongjiCamp/dto/request/CommentDto.java
  src/main/java/com/won/myongjiCamp/dto/request/PageDto.java
  src/main/java/com/won/myongjiCamp/dto/request/RecruitDto.java
  src/main/java/com/won/myongjiCamp/dto/request/ReportDto.java
  src/main/java/com/won/myongjiCamp/dto/request/TokenDto.java
  src/main/java/com/won/myongjiCamp/dto/response/BoardListResponseDto.java
  src/main/java/com/won/myongjiCamp/dto/response/CommentResponseDto.java
  src/main/java/com/won/myongjiCamp/dto/response/NotificationResponseDto.java
  src/main/java/com/won/myongjiCamp/dto/response/ResponseDto.java
  src/main/java/com/won/myongjiCamp/handler/CustomAuthenticationFailureHandler.java
  src/main/java/com/won/myongjiCamp/handler/CustomAuthenticationSuccessHandler.java
  src/main/java/com/won/myongjiCamp/handler/GlobalExceptionHandler.java
  src/main/java/com/won/myongjiCamp/service/CommentService.java
  src/main/java/com/won/myongjiCamp/service/FcmService.java
  src/main/java/com/won/myongjiCamp/service/RecruitService.java
  src/main/java/com/won/myongjiCamp/service/ReportService.java
  src/main/resources/application.yml
Labels: :hammer: Fix
